concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CI: true
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          envFilePath: ./envvars.for.actions

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install
        run: npm install

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.1
        with:
          envFilePath: ./envvars.for.actions

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - run: npm run coveralls

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'tagged version')
    steps:
      - uses: actions/checkout@v7
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          envFilePath: ./envvars.for.actions

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - run: npm run dist
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  dependabot:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
      repository-projects: read

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          skip-commit-verification: true

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Approve a PR if not already approved
        run: |
          gh pr checkout "$PR_URL"
            if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved.";
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Enable auto-merge for Dependabot PRs
        if: ${{ contains(github.event.pull_request.title, 'bump')}}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
